/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package turtle

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// CronJobListerExpansion allows custom methods to be added to
// CronJobLister.
type CronJobListerExpansion interface{}

// DaemonSetListerExpansion allows custom methods to be added to
// DaemonSetLister.
type DaemonSetListerExpansion interface{}

// DataCenterListerExpansion allows custom methods to be added to
// DataCenterLister.
type DataCenterListerExpansion interface{}

// DeploymentListerExpansion allows custom methods to be added to
// DeploymentLister.
type DeploymentListerExpansion interface{}

// EventListerExpansion allows custom methods to be added to
// EventLister.
type EventListerExpansion interface{}

// HPAListerExpansion allows custom methods to be added to
// HPALister.
type HPAListerExpansion interface{}

// IngressListerExpansion allows custom methods to be added to
// IngressLister.
type IngressListerExpansion interface{}

// JobListerExpansion allows custom methods to be added to
// JobLister.
type JobListerExpansion interface{}

// NamespaceListerExpansion allows custom methods to be added to
// NamespaceLister.
type NamespaceListerExpansion interface{}

// NodeListerExpansion allows custom methods to be added to
// NodeLister.
type NodeListerExpansion interface{}

// PVListerExpansion allows custom methods to be added to
// PVLister.
type PVListerExpansion interface{}

// PVCListerExpansion allows custom methods to be added to
// PVCLister.
type PVCListerExpansion interface{}

// PodListerExpansion allows custom methods to be added to
// PodLister.
type PodListerExpansion interface{}

// ReplicaSetListerExpansion allows custom methods to be added to
// ReplicaSetLister.
type ReplicaSetListerExpansion interface{}

// ServiceListerExpansion allows custom methods to be added to
// ServiceLister.
type ServiceListerExpansion interface{}

// StatefulSetListerExpansion allows custom methods to be added to
// StatefulSetLister.
type StatefulSetListerExpansion interface{}

// ZoneListerExpansion allows custom methods to be added to
// ZoneLister.
type ZoneListerExpansion interface{}
