/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package turtle

import (
	turtle "git.cloud2go.cn/reedition/turtle/api/pkg/apis/turtle"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ZoneLister helps list Zones.
type ZoneLister interface {
	// List lists all Zones in the indexer.
	List(selector labels.Selector) (ret []*turtle.Zone, err error)
	// Get retrieves the Zone from the index for a given name.
	Get(name string) (*turtle.Zone, error)
	ZoneListerExpansion
}

// zoneLister implements the ZoneLister interface.
type zoneLister struct {
	indexer cache.Indexer
}

// NewZoneLister returns a new ZoneLister.
func NewZoneLister(indexer cache.Indexer) ZoneLister {
	return &zoneLister{indexer: indexer}
}

// List lists all Zones in the indexer.
func (s *zoneLister) List(selector labels.Selector) (ret []*turtle.Zone, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*turtle.Zone))
	})
	return ret, err
}

// Get retrieves the Zone from the index for a given name.
func (s *zoneLister) Get(name string) (*turtle.Zone, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(turtle.Resource("zone"), name)
	}
	return obj.(*turtle.Zone), nil
}
