/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "git.cloud2go.cn/reedition/turtle/api/pkg/apis/turtle/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PVLister helps list PVs.
type PVLister interface {
	// List lists all PVs in the indexer.
	List(selector labels.Selector) (ret []*v1.PV, err error)
	// Get retrieves the PV from the index for a given name.
	Get(name string) (*v1.PV, error)
	PVListerExpansion
}

// pVLister implements the PVLister interface.
type pVLister struct {
	indexer cache.Indexer
}

// NewPVLister returns a new PVLister.
func NewPVLister(indexer cache.Indexer) PVLister {
	return &pVLister{indexer: indexer}
}

// List lists all PVs in the indexer.
func (s *pVLister) List(selector labels.Selector) (ret []*v1.PV, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.PV))
	})
	return ret, err
}

// Get retrieves the PV from the index for a given name.
func (s *pVLister) Get(name string) (*v1.PV, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("pv"), name)
	}
	return obj.(*v1.PV), nil
}
