/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "git.cloud2go.cn/reedition/turtle/api/pkg/apis/turtle/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PVCLister helps list PVCs.
type PVCLister interface {
	// List lists all PVCs in the indexer.
	List(selector labels.Selector) (ret []*v1.PVC, err error)
	// Get retrieves the PVC from the index for a given name.
	Get(name string) (*v1.PVC, error)
	PVCListerExpansion
}

// pVCLister implements the PVCLister interface.
type pVCLister struct {
	indexer cache.Indexer
}

// NewPVCLister returns a new PVCLister.
func NewPVCLister(indexer cache.Indexer) PVCLister {
	return &pVCLister{indexer: indexer}
}

// List lists all PVCs in the indexer.
func (s *pVCLister) List(selector labels.Selector) (ret []*v1.PVC, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.PVC))
	})
	return ret, err
}

// Get retrieves the PVC from the index for a given name.
func (s *pVCLister) Get(name string) (*v1.PVC, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("pvc"), name)
	}
	return obj.(*v1.PVC), nil
}
