/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	turtlev1 "git.cloud2go.cn/reedition/turtle/api/pkg/apis/turtle/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePods implements PodInterface
type FakePods struct {
	Fake *FakeTurtleV1
}

var podsResource = schema.GroupVersionResource{Group: "turtle", Version: "v1", Resource: "pods"}

var podsKind = schema.GroupVersionKind{Group: "turtle", Version: "v1", Kind: "Pod"}

// Get takes name of the pod, and returns the corresponding pod object, and an error if there is any.
func (c *FakePods) Get(name string, options v1.GetOptions) (result *turtlev1.Pod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(podsResource, name), &turtlev1.Pod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Pod), err
}

// List takes label and field selectors, and returns the list of Pods that match those selectors.
func (c *FakePods) List(opts v1.ListOptions) (result *turtlev1.PodList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(podsResource, podsKind, opts), &turtlev1.PodList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &turtlev1.PodList{ListMeta: obj.(*turtlev1.PodList).ListMeta}
	for _, item := range obj.(*turtlev1.PodList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pods.
func (c *FakePods) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(podsResource, opts))
}

// Create takes the representation of a pod and creates it.  Returns the server's representation of the pod, and an error, if there is any.
func (c *FakePods) Create(pod *turtlev1.Pod) (result *turtlev1.Pod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(podsResource, pod), &turtlev1.Pod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Pod), err
}

// Update takes the representation of a pod and updates it. Returns the server's representation of the pod, and an error, if there is any.
func (c *FakePods) Update(pod *turtlev1.Pod) (result *turtlev1.Pod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(podsResource, pod), &turtlev1.Pod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Pod), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePods) UpdateStatus(pod *turtlev1.Pod) (*turtlev1.Pod, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(podsResource, "status", pod), &turtlev1.Pod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Pod), err
}

// Delete takes name of the pod and deletes it. Returns an error if one occurs.
func (c *FakePods) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(podsResource, name), &turtlev1.Pod{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePods) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(podsResource, listOptions)

	_, err := c.Fake.Invokes(action, &turtlev1.PodList{})
	return err
}

// Patch applies the patch and returns the patched pod.
func (c *FakePods) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *turtlev1.Pod, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(podsResource, name, pt, data, subresources...), &turtlev1.Pod{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Pod), err
}
