/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	turtlev1 "git.cloud2go.cn/reedition/turtle/api/pkg/apis/turtle/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeZones implements ZoneInterface
type FakeZones struct {
	Fake *FakeTurtleV1
}

var zonesResource = schema.GroupVersionResource{Group: "turtle", Version: "v1", Resource: "zones"}

var zonesKind = schema.GroupVersionKind{Group: "turtle", Version: "v1", Kind: "Zone"}

// Get takes name of the zone, and returns the corresponding zone object, and an error if there is any.
func (c *FakeZones) Get(name string, options v1.GetOptions) (result *turtlev1.Zone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(zonesResource, name), &turtlev1.Zone{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Zone), err
}

// List takes label and field selectors, and returns the list of Zones that match those selectors.
func (c *FakeZones) List(opts v1.ListOptions) (result *turtlev1.ZoneList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(zonesResource, zonesKind, opts), &turtlev1.ZoneList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &turtlev1.ZoneList{ListMeta: obj.(*turtlev1.ZoneList).ListMeta}
	for _, item := range obj.(*turtlev1.ZoneList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested zones.
func (c *FakeZones) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(zonesResource, opts))
}

// Create takes the representation of a zone and creates it.  Returns the server's representation of the zone, and an error, if there is any.
func (c *FakeZones) Create(zone *turtlev1.Zone) (result *turtlev1.Zone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(zonesResource, zone), &turtlev1.Zone{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Zone), err
}

// Update takes the representation of a zone and updates it. Returns the server's representation of the zone, and an error, if there is any.
func (c *FakeZones) Update(zone *turtlev1.Zone) (result *turtlev1.Zone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(zonesResource, zone), &turtlev1.Zone{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Zone), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeZones) UpdateStatus(zone *turtlev1.Zone) (*turtlev1.Zone, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(zonesResource, "status", zone), &turtlev1.Zone{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Zone), err
}

// Delete takes name of the zone and deletes it. Returns an error if one occurs.
func (c *FakeZones) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(zonesResource, name), &turtlev1.Zone{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeZones) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(zonesResource, listOptions)

	_, err := c.Fake.Invokes(action, &turtlev1.ZoneList{})
	return err
}

// Patch applies the patch and returns the patched zone.
func (c *FakeZones) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *turtlev1.Zone, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(zonesResource, name, pt, data, subresources...), &turtlev1.Zone{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.Zone), err
}
