/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	turtlev1 "git.cloud2go.cn/reedition/turtle/api/pkg/apis/turtle/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHPAs implements HPAInterface
type FakeHPAs struct {
	Fake *FakeTurtleV1
}

var hpasResource = schema.GroupVersionResource{Group: "turtle", Version: "v1", Resource: "hpas"}

var hpasKind = schema.GroupVersionKind{Group: "turtle", Version: "v1", Kind: "HPA"}

// Get takes name of the hPA, and returns the corresponding hPA object, and an error if there is any.
func (c *FakeHPAs) Get(name string, options v1.GetOptions) (result *turtlev1.HPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(hpasResource, name), &turtlev1.HPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.HPA), err
}

// List takes label and field selectors, and returns the list of HPAs that match those selectors.
func (c *FakeHPAs) List(opts v1.ListOptions) (result *turtlev1.HPAList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(hpasResource, hpasKind, opts), &turtlev1.HPAList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &turtlev1.HPAList{ListMeta: obj.(*turtlev1.HPAList).ListMeta}
	for _, item := range obj.(*turtlev1.HPAList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hPAs.
func (c *FakeHPAs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(hpasResource, opts))
}

// Create takes the representation of a hPA and creates it.  Returns the server's representation of the hPA, and an error, if there is any.
func (c *FakeHPAs) Create(hPA *turtlev1.HPA) (result *turtlev1.HPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(hpasResource, hPA), &turtlev1.HPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.HPA), err
}

// Update takes the representation of a hPA and updates it. Returns the server's representation of the hPA, and an error, if there is any.
func (c *FakeHPAs) Update(hPA *turtlev1.HPA) (result *turtlev1.HPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(hpasResource, hPA), &turtlev1.HPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.HPA), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHPAs) UpdateStatus(hPA *turtlev1.HPA) (*turtlev1.HPA, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(hpasResource, "status", hPA), &turtlev1.HPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.HPA), err
}

// Delete takes name of the hPA and deletes it. Returns an error if one occurs.
func (c *FakeHPAs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(hpasResource, name), &turtlev1.HPA{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHPAs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(hpasResource, listOptions)

	_, err := c.Fake.Invokes(action, &turtlev1.HPAList{})
	return err
}

// Patch applies the patch and returns the patched hPA.
func (c *FakeHPAs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *turtlev1.HPA, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(hpasResource, name, pt, data, subresources...), &turtlev1.HPA{})
	if obj == nil {
		return nil, err
	}
	return obj.(*turtlev1.HPA), err
}
