/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "git.cloud2go.cn/reedition/turtle/api/pkg/apis/turtle/v1"
	scheme "git.cloud2go.cn/reedition/turtle/api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HPAsGetter has a method to return a HPAInterface.
// A group's client should implement this interface.
type HPAsGetter interface {
	HPAs() HPAInterface
}

// HPAInterface has methods to work with HPA resources.
type HPAInterface interface {
	Create(*v1.HPA) (*v1.HPA, error)
	Update(*v1.HPA) (*v1.HPA, error)
	UpdateStatus(*v1.HPA) (*v1.HPA, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.HPA, error)
	List(opts metav1.ListOptions) (*v1.HPAList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.HPA, err error)
	HPAExpansion
}

// hPAs implements HPAInterface
type hPAs struct {
	client rest.Interface
}

// newHPAs returns a HPAs
func newHPAs(c *TurtleV1Client) *hPAs {
	return &hPAs{
		client: c.RESTClient(),
	}
}

// Get takes name of the hPA, and returns the corresponding hPA object, and an error if there is any.
func (c *hPAs) Get(name string, options metav1.GetOptions) (result *v1.HPA, err error) {
	result = &v1.HPA{}
	err = c.client.Get().
		Resource("hpas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HPAs that match those selectors.
func (c *hPAs) List(opts metav1.ListOptions) (result *v1.HPAList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.HPAList{}
	err = c.client.Get().
		Resource("hpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hPAs.
func (c *hPAs) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("hpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a hPA and creates it.  Returns the server's representation of the hPA, and an error, if there is any.
func (c *hPAs) Create(hPA *v1.HPA) (result *v1.HPA, err error) {
	result = &v1.HPA{}
	err = c.client.Post().
		Resource("hpas").
		Body(hPA).
		Do().
		Into(result)
	return
}

// Update takes the representation of a hPA and updates it. Returns the server's representation of the hPA, and an error, if there is any.
func (c *hPAs) Update(hPA *v1.HPA) (result *v1.HPA, err error) {
	result = &v1.HPA{}
	err = c.client.Put().
		Resource("hpas").
		Name(hPA.Name).
		Body(hPA).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *hPAs) UpdateStatus(hPA *v1.HPA) (result *v1.HPA, err error) {
	result = &v1.HPA{}
	err = c.client.Put().
		Resource("hpas").
		Name(hPA.Name).
		SubResource("status").
		Body(hPA).
		Do().
		Into(result)
	return
}

// Delete takes name of the hPA and deletes it. Returns an error if one occurs.
func (c *hPAs) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("hpas").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hPAs) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("hpas").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched hPA.
func (c *hPAs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.HPA, err error) {
	result = &v1.HPA{}
	err = c.client.Patch(pt).
		Resource("hpas").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
